{% set name = "esbonio" %}
{% set version = "0.16.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esbonio-{{ version }}.tar.gz
  sha256: acab2e16c6cf8f7232fb04e0d48514ce50566516b1f6fcf669ccf2f247e8b10f

build:
  entry_points:
    - esbonio = esbonio.__main__:main
    - esbonio-sphinx = esbonio.lsp.sphinx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - platformdirs
    - pygls >=1.1.0
    - pyspellchecker
    - python >={{ python_min }}
    - sphinx
    - typing-extensions

test:
  imports:
    - esbonio.lsp
  commands:
    - pip check
    - esbonio --help
    - esbonio-sphinx --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://swyddfa.github.io/esbonio/
  summary: A Language Server for Sphinx projects.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/swyddfa/esbonio

extra:
  recipe-maintainers:
    - alcarney
