{% set name = "esbonio" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esbonio-{{ version }}.tar.gz
  sha256: 9d1c3d3e074b3f7fe285147cd713fbda0290472864756772020aebf19f5935c0

build:
  entry_points:
    - esbonio = esbonio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - aiosqlite
    - platformdirs
    - docutils
    - pygls >=2.0
    - tomli
    - websockets

test:
  imports:
    - esbonio.server
    - esbonio.sphinx_agent.types
  commands:
    - pip check
    - esbonio --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://swyddfa.github.io/esbonio/
  summary: A Language Server for Sphinx projects.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/swyddfa/esbonio

extra:
  recipe-maintainers:
    - alcarney
