{% set name = "esbonio" %}
{% set version = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esbonio-{{ version }}.tar.gz
  sha256: 72824a3373f293f5f4e2ad2bbd6a242010344e27d5b1cdffb21fb6fa37dc5864

build:
  entry_points:
    - esbonio = esbonio.__main__:main
    - esbonio-sphinx = esbonio.lsp.sphinx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - appdirs
    - pygls >=1.0.0
    - pyspellchecker
    - python >=3.7
    - sphinx
    - typing-extensions

test:
  imports:
    - esbonio.lsp
  commands:
    - pip check
    - esbonio --help
    - esbonio-sphinx --help
  requires:
    - pip

about:
  home: https://swyddfa.github.io/esbonio/
  summary: A Language Server for Sphinx projects.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/swyddfa/esbonio

extra:
  recipe-maintainers:
    - alcarney
